### ISSUE TITLE
Round to floor when div?

### ISSUE THREAD

**Issue by devnomic** [bpierre/dnum#1]
````
format([49998805n, 9], { digits: 4 } );
// return 0.05
// expected 0.0499
````
UX issue with normal rounding case:
The user use a little bit of gas token to do a transaction, but the displayed amount of balance still same because formatting is using normal round. 

Change `divideAndRound` to floor div implementation will fix this.
What do you think?

**Comment by bpierre** [comment]
Thanks for opening an issue!

It looks a little bit counter intuitive in this case, but I think the current behavior works well as the default, i.e. we round to the nearest tens rather than rounding up or down, from the right to left:

```
049998805  // 5 is the threshold at which we round up…
04999881_  // 0 becomes 1, and gets rounded down…
0499988__  // 8 stays 8, and gets rounded up…
049999___  // 8 becomes 9, and gets rounded up…
0499T____  // 9 becomes 10 (T) and pushes the next digit up…
049T_____  // 9 becomes 10 (T), we are now at 4 digits, but T needs to get removed…
04T______  // 9 becomes 10 (T) and pushes the next digit up…
05_______  // 4 becomes 5. No 10 (T) to remove anymore, and we are below 4 digits, we stop.
```

But now I am wondering, would it be useful to have an option to specify the rounding method?

There is already a `round` option on [`setDecimals()`](https://github.com/bpierre/dnum#setdecimalsvalue-decimals-options) that could be used to achieve this:

```tsx
const value = [49998805n, 9]
dn.format(dn.setDecimals(value, 4, { round: false })) // 0.4999
```

Demo: https://codesandbox.io/s/dnum-rounding-ukry8m

Maybe we could add a `rounding` option to relevant methods, that would look like `"round" | "floor" | "ceil"` and default to `round`. I am just wondering if having the feature would be worth the cost of adding it, since I am trying to keep the library as small as possible. What do you think?

**Comment by devnomic** [comment]
Thank you for the reply with explanation,
Yeah maybe stick with current rounding for now, probably not worth the cost.
i made a fork that change the divideAndRound to floor div at the moment.

**Comment by bpierre** [comment]
@devnomic I changed the way decimals get rounded to the specified number of digits, which allowed to implement the option easily: https://github.com/bpierre/dnum/releases/tag/v2.3.0

You can now pass `decimalsRounding`:

```tsx
format(
  [49998805n, 9],
  { digits: 4, decimalsRounding: "ROUND_DOWN" }
) // 0.0499
```

Let me know if that works for your case!

**Comment by devnomic** [comment]
Works very great! Thank you!
